version: "3.9"
services:
  db_postgres:
    image: postgres:latest
    container_name: postgresql_db
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_URL}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5431:5432"